### ISSUE TITLE
telegraf keeps restarting

### ISSUE THREAD

**Issue by petercockroach** [liveaverage/dc-powerwall-dashboard#3]
The telegraf service keeps restarting and eventually seems to hang. From the logs, I keep seeing "PWcookie.txt No such file or directory". What am I missing?

- I followed the steps documented, with the only change being that I was getting an error mapping `/srv/powerwall/influxdb:/var/lib/influxdb:z` since this path didn't exist. I created ./srv/powerwall/influxdb in the working directory to workaround this.
- I made sure to change permissions on the telegraf folder as instructed
- I created a .env file (which currently just has some made up data for debugging purposes)
[telegraf.log](https://github.com/liveaverage/dc-powerwall-dashboard/files/7522807/telegraf.log)

Thanks for looking!

**Comment by liveaverage** [comment]
telegraf appears to be exiting because your cookie isn't being generated in a local dir, likely due to my poor documentation:

```
grep: /tmp/cookie/PWcookie.txt: No such file or directory
```
I updated the readme to include a couple extra steps you need to execute:
```
mkdir powerwall_auth
chmod -R ug+rw telegraf/ powerwall_auth/
```
Once done, try a quick `docker-compose stop && docker-compose up` to see if that addresses it?

**Comment by petercockroach** [comment]
Looks like it's working now. Thank you!
