### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by natrlhy** [liveaverage/dc-powerwall-dashboard#7]
If I wanted to move to this project from docker-powerwall-dashboard what's the best way to do so and retain all my historical data?

**Comment by liveaverage** [comment]
The major versions haven't really changed between the deployments, so stopping the current all-in-one container, copying current folder to a new destination (corresponding to your mapped directory: https://github.com/liveaverage/dc-powerwall-dashboard/blob/master/docker-compose.yaml#L30), and starting the new service stack is all that's required.

**Comment by natrlhy** [comment]
Does it need this still?
```
extra_hosts:
    - 'powerwall:1.2.3.4'

**Comment by natrlhy** [comment]
Mind helping me ensure my volumes, etc are going to be accurate if I simply just copy the old project to the new dc-powerwall-dashboard docker folder?
 Current docker file:

```
version: '3.3'
services:
    powerwall-dashboard:
        restart: always
        container_name: powerdash
        extra_hosts:
            - 'powerwall:1.2.3.4'
        ports:
            - '3001:3000'
        environment:
            - POWERWALL_PASS=ABC123
            - POWERWALL_LOCATION=lat=56.78910&lon=-111.22222
            - GRAFANA_DASHBOARD_URL=https://raw.githubusercontent.com/liveaverage/docker-powerwall-dashboard/master/graf_dash.json
        volumes:
            - './influx-data:/var/lib/influxdb'
            - './grafana-data:/var/lib/grafana'
        image: liveaverage/powerwall-dashboard:latest

**Comment by liveaverage** [comment]
The right side of the volume mapping should remain consistent. The left side of the volume mapping should match values previously used in your `docker run` command and varies depending on where your data resides (https://github.com/liveaverage/docker-powerwall-dashboard#usage) :

```
	-v ${LOCAL_INFLUXDB_PATH}:/var/lib/influxdb:z \
	-v ${LOCAL_GRAFANA_PATH}:/var/lib/grafana:z \
```

I strongly suggest copying the existing `influxdb` directory to a new location first, then reference _that_ directory vs. your original.

**Comment by natrlhy** [comment]
I stopped my old container and copied the old influx-data to the new `influxdb` directory after doing the git clone. I also create a .env file with my variables in the same working directory as my `~/docker/dc-powerwall-dashboard` directory. Upon startup I get:
```
docker-compose up -d
WARNING: The POWERWALL_PASS variable is not set. Defaulting to a blank string.
WARNING: The VIRTUAL_HOST variable is not set. Defaulting to a blank string.
WARNING: The VIRTUAL_PORT variable is not set. Defaulting to a blank string.
```
I'll resort to hard coding it all in the `docker-compose.yml` file next.

EDIT: Had a typo in my .env file for the `POWERWALL_PASS ` so got that fixed. :)

Are the VIRTUAL_HOST ports needed or can I comment them out?

**Comment by liveaverage** [comment]
The actual use of env vars is documented in the README. I'll add `VIRTUAL_HOST` and `VIRTUAL_PORT` to the README as optional params, but it's very specific to use alongside nginx-proxy (https://github.com/nginx-proxy/nginx-proxy). In the future, please open up new issues for any new problems encountered.

**Comment by natrlhy** [comment]
Just for anyone else that may read this, my process was this:

1. Stop my old powerdash container
2. Backup entire contents of my old `influx-data` folder
3. Copy entire contents of old `influx-data` to new: `cp -r ../../PowerDash/influx-data/* .` (I was in the `dc-powerwall-dashboard\influxdb` dir already).
4. Modify the dc-powerwall-dashboard/.env file to my settings
5. Modify the docker-compose.yml file to my liking
6. Start the new container

My `docker-compose.yml` file:

```
version: "3.7"
services:
  telegraf:
    image: docker.io/telegraf:1.19
    labels:
      io.containers.autoupdate: image
    container_name: pw_telegraf
    command:
      - "bash"
      - "-xe"
      - "/tmp/entrypoint.sh"
    restart: unless-stopped
    environment:
      - POWERWALL_PASS=${POWERWALL_PASS}
      - POWERWALL_LOCATION=${POWERWALL_LOCATION}
    volumes:
      - ./telegraf/entrypoint.sh:/tmp/entrypoint.sh:z
      - ./telegraf/etc:/etc/telegraf:z
      - ./powerwall_auth:/tmp/cookie:z
    extra_hosts:
      - powerwall:${POWERWALL_IP}
  influxdb:
    image: docker.io/influxdb:1.8
    labels:
      io.containers.autoupdate: image
    container_name: pw_influxdb
    restart: unless-stopped
    volumes:
        - ./influxdb/etc:/etc/influxdb
        - ./influxdb:/var/lib/influxdb:z
  grafana:
    image: docker.io/grafana/grafana:7.5.10
    labels:
      io.containers.autoupdate: image
    container_name: pw_grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=powerwall
      - GF_SECURITY_ADMIN_PASSWORD=powerwall
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - POWERWALL_LOCATION=${POWERWALL_LOCATION}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./grafana/baked:/var/lib/grafana/dashboards:z
